
services:
  app:
    build: .
    container_name: app_stone
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=stone_db
      - SPARK_DRIVER_MEMORY=2g

  db:
    image: postgres:15-alpine
    container_name: db_stone
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stone_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: